# This playbook will install windows updates of all the categories on the machines for the group mentioned as the argument and reboot the server
# The following command should be run to install the updates
# ansible-playbook win-update-all.yml --ask-vault-pass --extra-vars "group=[group_name | hostname]"

- hosts: '{{ group }}'
  gather_facts: no
  tasks:

    - name: Set Facts
      set_fact:
        cntr_user: "{{ lookup('env','USER') }}"
        cntr_hostname: "{{ lookup('env','HOSTNAME') }}"

    - name: Find all avaiable updates.
      win_updates:
        category_names:
          - Application
          - Connectors
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - ServicePacks
          - Tools
          - UpdateRollups
          - CriticalUpdates
          - SecurityUpdates
          - Updates
          - UpdateRollups
        state: searched
        log_path: c:\ansible_wui_list.txt
      register: found_updates
      tags: find_updates

    - name: Display (all) updates.
      debug: var=found_update

    - name: Install (all) the updates.
      win_updates:
        category_names:
          - Application
          - Connectors
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - ServicePacks
          - Tools
          - UpdateRollups
          - CriticalUpdates
          - SecurityUpdates
          - Updates
          - UpdateRollups
        state: installed
        log_path: c:\ansible_wui_installed.txt
      register: check_finish
      tags: installed_updates